# Generated by Django 4.1.1 on 2022-09-11 17:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unq', models.CharField(default=uuid.UUID('eb42b8e1-8235-4d61-acbe-16e481551e2e'), max_length=255)),
                ('num', models.CharField(max_length=255)),
                ('route', models.CharField(choices=[('R1', 'R1'), ('R2', 'R2'), ('R3', 'R3')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('rid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('rname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Stops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=255)),
                ('sroute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmain.route')),
            ],
        ),
        migrations.CreateModel(
            name='Buses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unq', models.CharField(default=uuid.UUID('547a3060-6e77-448c-b80d-3d799ab28d16'), max_length=255)),
                ('bnum', models.CharField(max_length=255)),
                ('b_cur_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmain.stops')),
                ('broute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmain.route')),
            ],
        ),
    ]
