# Generated by Django 4.1.1 on 2022-09-12 17:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bstop',
            name='unq',
            field=models.CharField(default=uuid.UUID('d23eaedb-1452-4f61-8df9-9e2446006345'), max_length=255),
        ),
        migrations.AlterField(
            model_name='buses',
            name='unq',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
